AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that includes all nested stacks

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<your-bucket>.s3.amazonaws.com/vpc.yml

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<your-bucket>.s3.amazonaws.com/iam.yml

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<your-bucket>.s3.amazonaws.com/ec2.yml
      Parameters:
        SubnetIds: !GetAtt VPCStack.Outputs.SubnetIds
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        KeyName: !Ref KeyName
        InstanceProfileName: !GetAtt IAMStack.Outputs.InstanceProfileName

        Resources:

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/your-bucket-name/s3.yml
      Parameters:
        # Add parameters if required by s3.yml

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/your-bucket-name/rds.yml
      Parameters:
        DBInstanceIdentifier: mydbinstance
        DBName: mydatabase
        MasterUsername: admin
        MasterUserPassword: mySecurePassword123
