AWSTemplateFormatVersion: '2010-09-09'
Description: RDS instance

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet Group for RDS
      SubnetIds:
        - subnet-xxxxxxx
        - subnet-yyyyyyy

  MyRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydb
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: password1234
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref RDSSubnetGroup
      PubliclyAccessible: true

